### PR TITLE
Nxviz

### PR DESCRIPTION
**Pull request by leotrs**
Added visualization code to `pops.display`.

Now `display` shows the same layout always, rather than just calling`nx.draw_spring` which generates a randomized layout.

There are also now two ways of running a task. For either, one must first call `pop.initialize_task`, which now doesn't run through the task, but only sets up the environment object. If we want to run the whole task, we should call `run_task` which sees it done until the end and distributes rewards, as usual. The new way of running the task is step-by-step by repeatedly calling `step_task` which executes only one message passing between neighbors. Only it the recipient is the target, `step_task` distributes rewards (there's no need to do it manually). Existing tests on /tests have been modified to act accordingly and all tests have passed. 

For all this, some internal changes have been made, such as now the Environment object holds a reference to the node coordinates for stable display, and it also holds a reference to the current running Task object. There is also the internal `pop._task_active` which returns True if there is a current task running. This encapsulates what was talked about in the past, regarding the Environment keeping track of whether or not it's currently running a task.

### CODE REVIEW

**Comment by bhtucker** [comment]
Perhaps `run_task` can initiate a task if necessary, so we still get 1-line task execution in all calling code?

**Comment by leotrs** [comment]
WAIT, this wasn't ready for merging!

**Comment by bhtucker** [comment]
@Leockard this merge was a result of sphinx being branched from this

**Comment by leotrs** [comment]
I see, so it only performed the last merge, from sphinx to master?

I just checked, and everything seems all right.

**Comment by bhtucker** [comment]
Yep, all the commits in this PR are also in that PR so merging that PR accomplishes this PR's 'requested merge'

**Pull request merged**
